sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t 501stalpha1/rpn-calculator .

script:
  - docker run -t 501stalpha1/rpn-calculator rspec

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push 501stalpha1/rpn-calculator

branches:
  only:
    - master
